title: NatScience
author: natcmsn
email: your-email@domain.com
description: Here you will find random facts and interesting stuff about sciency stuff.
  theme: minima
theme: minima


# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
